services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  db-chat-ollama:
    image: postgres:latest
    container_name: db-chat-ollama
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chat1234
      POSTGRES_DB: chat
    volumes:
      - ./db-chat-ollama:/var/lib/postgresql/data

volumes:
  ollama:
    driver: local
  db-chat-ollama:
    driver: local
