/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreateChatResponseFromDiscriminatorValue, serializeCreateChatRequest, serializeCreateChatResponse, type CreateChatRequest, type CreateChatResponse } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/CreateChat
 */
export interface CreateChatRequestBuilder extends BaseRequestBuilder<CreateChatRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateChatResponse>}
     */
     post(body: CreateChatRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateChatResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateChatRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CreateChatRequestBuilderUriTemplate = "{+baseurl}/api/CreateChat";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateChatRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateChatRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createCreateChatResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateChatRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
