/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSendMessageResponseFromDiscriminatorValue, serializeSendMessageRequest, serializeSendMessageResponse, type SendMessageRequest, type SendMessageResponse } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/SendMessage
 */
export interface SendMessageRequestBuilder extends BaseRequestBuilder<SendMessageRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SendMessageResponse>}
     */
     post(body: SendMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SendMessageResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SendMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SendMessageRequestBuilderUriTemplate = "{+baseurl}/api/SendMessage";
/**
 * Metadata for all the requests in the request builder.
 */
export const SendMessageRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SendMessageRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSendMessageResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSendMessageRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
