/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  GetAllMessagesRequestBuilderRequestsMetadata,
  type GetAllMessagesRequestBuilder,
} from "./getAllMessages";
// @ts-ignore
import {
  SendMessageRequestBuilderRequestsMetadata,
  type SendMessageRequestBuilder,
} from "./sendMessage";
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from "@microsoft/kiota-abstractions";

/**
 * Builds and executes requests for operations under /messages
 */
export interface MessagesRequestBuilder
  extends BaseRequestBuilder<MessagesRequestBuilder> {
  /**
   * The GetAllMessages property
   */
  get getAllMessages(): GetAllMessagesRequestBuilder;
  /**
   * The SendMessage property
   */
  get sendMessage(): SendMessageRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MessagesRequestBuilderUriTemplate = "{+baseurl}/messages";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MessagesRequestBuilderNavigationMetadata: Record<
  Exclude<keyof MessagesRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  getAllMessages: {
    requestsMetadata: GetAllMessagesRequestBuilderRequestsMetadata,
  },
  sendMessage: {
    requestsMetadata: SendMessageRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
