/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatsRequestBuilderNavigationMetadata, type ChatsRequestBuilder } from './chats/';
// @ts-ignore
import { MessagesRequestBuilderNavigationMetadata, type MessagesRequestBuilder } from './messages/';
// @ts-ignore
import { ModelsRequestBuilderNavigationMetadata, type ModelsRequestBuilder } from './modelsRequests/';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface Client extends BaseRequestBuilder<Client> {
    /**
     * The chats property
     */
    get chats(): ChatsRequestBuilder;
    /**
     * The messages property
     */
    get messages(): MessagesRequestBuilder;
    /**
     * The models property
     */
    get models(): ModelsRequestBuilder;
}
/**
 * Instantiates a new {@link Client} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultSerializer(TextSerializationWriterFactory);
    registerDefaultSerializer(FormSerializationWriterFactory);
    registerDefaultSerializer(MultipartSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    registerDefaultDeserializer(TextParseNodeFactory);
    registerDefaultDeserializer(FormParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "http://localhost:5010";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<Client>(requestAdapter, pathParameters, ClientNavigationMetadata, undefined);
}
/**
 * Uri template for the request builder.
 */
export const ClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ClientNavigationMetadata: Record<Exclude<keyof Client, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chats: {
        navigationMetadata: ChatsRequestBuilderNavigationMetadata,
    },
    messages: {
        navigationMetadata: MessagesRequestBuilderNavigationMetadata,
    },
    models: {
        navigationMetadata: ModelsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
