/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CreateChatRequestBuilderRequestsMetadata, type CreateChatRequestBuilder } from './createChat/';
// @ts-ignore
import { GetAllChatsRequestBuilderRequestsMetadata, type GetAllChatsRequestBuilder } from './getAllChats/';
// @ts-ignore
import { GetAllMessagesRequestBuilderRequestsMetadata, type GetAllMessagesRequestBuilder } from './getAllMessages/';
// @ts-ignore
import { PingRequestBuilderRequestsMetadata, type PingRequestBuilder } from './ping/';
// @ts-ignore
import { SendMessageRequestBuilderRequestsMetadata, type SendMessageRequestBuilder } from './sendMessage/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The CreateChat property
     */
    get createChat(): CreateChatRequestBuilder;
    /**
     * The GetAllChats property
     */
    get getAllChats(): GetAllChatsRequestBuilder;
    /**
     * The GetAllMessages property
     */
    get getAllMessages(): GetAllMessagesRequestBuilder;
    /**
     * The Ping property
     */
    get ping(): PingRequestBuilder;
    /**
     * The SendMessage property
     */
    get sendMessage(): SendMessageRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    createChat: {
        requestsMetadata: CreateChatRequestBuilderRequestsMetadata,
    },
    getAllChats: {
        requestsMetadata: GetAllChatsRequestBuilderRequestsMetadata,
    },
    getAllMessages: {
        requestsMetadata: GetAllMessagesRequestBuilderRequestsMetadata,
    },
    ping: {
        requestsMetadata: PingRequestBuilderRequestsMetadata,
    },
    sendMessage: {
        requestsMetadata: SendMessageRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
