/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  CreateChatRequestBuilderRequestsMetadata,
  type CreateChatRequestBuilder,
} from "./createChat";
// @ts-ignore
import {
  GetAllChatsRequestBuilderRequestsMetadata,
  type GetAllChatsRequestBuilder,
} from "./getAllChats";
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from "@microsoft/kiota-abstractions";

/**
 * Builds and executes requests for operations under /chats
 */
export interface ChatsRequestBuilder
  extends BaseRequestBuilder<ChatsRequestBuilder> {
  /**
   * The CreateChat property
   */
  get createChat(): CreateChatRequestBuilder;
  /**
   * The GetAllChats property
   */
  get getAllChats(): GetAllChatsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatsRequestBuilderUriTemplate = "{+baseurl}/chats";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatsRequestBuilderNavigationMetadata: Record<
  Exclude<keyof ChatsRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  createChat: {
    requestsMetadata: CreateChatRequestBuilderRequestsMetadata,
  },
  getAllChats: {
    requestsMetadata: GetAllChatsRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
