/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GetAvailableModelsRequestBuilderRequestsMetadata, type GetAvailableModelsRequestBuilder } from './getAvailableModels/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /models
 */
export interface ModelsRequestBuilder extends BaseRequestBuilder<ModelsRequestBuilder> {
    /**
     * The GetAvailableModels property
     */
    get getAvailableModels(): GetAvailableModelsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ModelsRequestBuilderUriTemplate = "{+baseurl}/models";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ModelsRequestBuilderNavigationMetadata: Record<Exclude<keyof ModelsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    getAvailableModels: {
        requestsMetadata: GetAvailableModelsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
