/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createIGetAllChatsResponseFromDiscriminatorValue, type IGetAllChatsResponse } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /chats/GetAllChats
 */
export interface GetAllChatsRequestBuilder extends BaseRequestBuilder<GetAllChatsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IGetAllChatsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IGetAllChatsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetAllChatsRequestBuilderUriTemplate = "{+baseurl}/chats/GetAllChats";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetAllChatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetAllChatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createIGetAllChatsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
