/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IPingResponse}
 */
// @ts-ignore
export function createIPingResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIPingResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIPingResponse(iPingResponse: Partial<IPingResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { iPingResponse.message = n.getStringValue(); },
    }
}
export interface IPingResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The message property
     */
    message?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIPingResponse(writer: SerializationWriter, iPingResponse: Partial<IPingResponse> | undefined | null = {}) : void {
    if (iPingResponse) {
        writer.writeStringValue("message", iPingResponse.message);
        writer.writeAdditionalData(iPingResponse.additionalData);
    }
}
/* tslint:enable */
/* eslint-enable */
