/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createIPingResponseFromDiscriminatorValue, type IPingResponse } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Ping
 */
export interface PingRequestBuilder extends BaseRequestBuilder<PingRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IPingResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IPingResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IPingResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IPingResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PingRequestBuilderUriTemplate = "{+baseurl}/api/Ping";
/**
 * Metadata for all the requests in the request builder.
 */
export const PingRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createIPingResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: PingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createIPingResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
