/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGetModelsResponseFromDiscriminatorValue, type GetModelsResponse } from '../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /models/GetAvailableModels
 */
export interface GetAvailableModelsRequestBuilder extends BaseRequestBuilder<GetAvailableModelsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetModelsResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GetModelsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetAvailableModelsRequestBuilderUriTemplate = "{+baseurl}/models/GetAvailableModels";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetAvailableModelsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetAvailableModelsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createGetModelsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
